import { Item } from '@adventure-bot/game/equipment'
import {
  alchemistsRing,
  amuletOfAttack,
  amuletOfProtection,
  assassinLeathers,
  berserkerHides,
  buckler,
  chainArmor,
  dagger,
  kiteShield,
  leatherArmor,
  longsword,
  mace,
  plateArmor,
  potionOfHaste,
  potionOfHealing,
  potionOfMight,
  potionOfProtection,
  potionOfSlaying,
  potionOfVigor,
  ringOfAttack,
  ringOfHaste,
  roguesBrew,
  roguesRing,
  towerShield,
  travelersRing,
  unidentifiedPotion,
  venomousBlade,
  warAxe,
} from '@adventure-bot/game/equipment/items'
import { weightedTable } from '@adventure-bot/game/utils'

export function randomChestItem(): Item {
  return weightedTable<() => Item>([
    [0.1, venomousBlade],
    [0.1, amuletOfAttack],
    [0.1, amuletOfProtection],
    [0.1, ringOfAttack],
    [0.1, roguesRing],
    [0.1, ringOfHaste],
    [0.3, plateArmor],
    [0.3, assassinLeathers],
    [0.3, berserkerHides],
    [0.5, towerShield],
    [0.5, warAxe],
    [0.5, potionOfMight],
    [0.5, potionOfProtection],
    [0.5, potionOfSlaying],
    [0.5, roguesBrew],
    [0.5, potionOfVigor],
    [0.5, potionOfHaste],
    [1, alchemistsRing],
    [1, chainArmor],
    [1, kiteShield],
    [1, longsword],
    [1, mace],
    [1, potionOfHealing],
    [1, travelersRing],
    [1, unidentifiedPotion],
    [1.2, buckler],
    [1.2, leatherArmor],
    [1.3, dagger],
  ])()
}
