export const zombieNames = `
Tanya Forbes
Houston Snyder
Sincere Sampson
Lorena Terry
Jessie Duke
Eddie Bray
Efrain Shannon
Shyann Decker
Gavyn Bird
Vaughn Horn
Ross Braun
Jaidyn Barnett
Taniyah Dunn
Katie Peters
Brett Dickerson
Nelson Meyers
Keith Oconnell
Christine Oconnor
Summer Peters
Luka Holland
Madelyn Mcdonald
Fiona Roberts
Maximo Kennedy
Kasey Ferguson
Kaylee Ball
Ainsley Gill
Kamden Murphy
Katelyn Grant
Eliana Bridges
Dayanara Gibson
Sanai Mcgee
Rebekah Pruitt
Heaven Fernandez
Harry Martin
Rebekah Weber
Kendrick Bird
Dakota Nash
Josiah Meza
Yahir Hanson
Elaina Osborn
Chaz Alexander
Giovanna Barber
Amira Hess
Juliet Liu
Trevin Daugherty
Aliza Estes
Ruben Wallace
Shannon Harrison
Ayaan Curry
Tomas Tapia
Brayan Green
Arthur Mercado
Tatum Peters
Lewis Krause
Jessica Hobbs
Emilia Dyer
Emery Stewart
Baylee Burch
Kaitlin Salazar
Karlee Mercer
Donavan Neal
Beatrice Martinez
Kamari Christensen
Amirah Lowe
Rodolfo Christian
Freddy Stephenson
Yurem Dennis
Imani Frazier
Micaela Mayer
Leticia Mcdonald
Sterling Lowery
Alejandro Maxwell
Messiah Powers
Heaven Black
Eliza Valentine
Julius Grant
Kayden Bentley
Finley Mckee
Nylah Merritt
Aiden Hobbs
Angelique Roach
Danica Bradley
Dax Hendricks
Milton Grimes
Vance Forbes
Wesley Lowery
Duncan Dillon
Kelly Brown
Dylan Bishop
Ray Irwin
Rowan Foster
Arianna Carter
Kai Hatfield
Maurice Lam
Nikolai Malone
Noelle Villegas
Livia Burnett
Keshawn Knight
Peter Beasley
Essence Duffy
`
  .split('\n')
  .filter(Boolean)
