name: Build and Deploy

on:
  push:
    branches: [main, fix-build] # TODO: fix-build branch, for testing only.
    
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: game
          path: packages/game/.build
      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: packages/web/.next

  deploy:
    needs: [build]
    environment: production
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - name: Start
        run: >
          pm2 flush && 
          DATABASE_PATH=~/.adventure-bot
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          pm2 start
