name: Clean ✨
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - run: find /tmp/ -name "yarn*" ! -readable -prune -o -print -mtime +1 -type f -exec rm {} \; > /dev/null
