name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: adventure-bot

    - name: 'Start game'
    - run: yarn game start
