name: Deploy

on:
  push:
    branches: [main]
    
jobs:

  deploy:
    environment: production
    runs-on: [self-hosted, production]
    concurrency: production

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Start
        run: >
          pm2 flush && 
          DATABASE_PATH=~/.adventure-bot-dev
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          AWS_S3_HOST=${{ secrets.AWS_S3_HOST }}
          pm2 start
