name: Deploy Dev

on:
  push:
    branches: [enable-redux-devtools]
    
jobs:

  deploy:
    environment: development
    runs-on: [self-hosted, development]
    concurrency: 
      group: development
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Start
        run: >
          pm2 flush && 
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          AWS_S3_HOST=${{ secrets.AWS_S3_HOST }}
          pm2 start --env development
