name: Format

on:
  workflow_run:
    workflows: ["Build"]
    types: 
      - completed
    
jobs:

  format:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Format
    runs-on: self-hosted
    needs: [build]

    steps:
      - run: yarn format:check
