name: Lint

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main, brian-gates/issue130] # TODO: remove this
    types: 
      - completed
    
jobs:

  lint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Lint
    runs-on: self-hosted
    needs: [build]

    steps:
      - run: yarn lint
